version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: sales_administration_11_11
    volumes:
      - ./postgres:/var/lib/postgresql/data